### ISSUE TITLE
Subscriptions are missing keepalives

### ISSUE THREAD

**Issue by daveoconnor** [tartiflette/tartiflette-aiohttp#123]
Been meaning to post this for a while after discussing it in the chat. I'd been having issues with the websocket connection closing and reopening - thanks to apollo reconnect - every ~50 seconds and not being able to determine why. After doing some research it seems that norm is that the server sends a keepalive.

https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md

This isn't majorly important at the moment and shouldn't be a big change so I'll try to look into it at some point in the future if no one else does, but it might be a while before I can get to it. Unit tests for subscriptions would be a big help in making that something that's safer to work on without fear of breaking things.

For anyone who comes across this issue in the meantime I've been able to implement a workaround on the apollo client side using a websocket link:

```
const subscriptionClient = new SubscriptionClient(this.wsdomain, {
	reconnect: true,
	lazy: true,
        options: {
		reconnect: true,
		lazy: true,
//		... other options ...
	}
});

setInterval(() => {
	if (subscriptionClient.status === 1) {
		subscriptionClient.client.send('{"type":"ka"}');
	 }
}, 40000);
const wsLink = new WebSocketLink(subscriptionClient);
```

Thanks!

**Comment by Maximilien-R** [comment]
Hi @daveoconnor,

I did a little PR (#124) that should introduce this feature to `tartiflette-aiohttp`.

There is a test version that include this feature which is available through:
```bash
$ pip install -i https://test.pypi.org/simple/ tartiflette-aiohttp==1.3.1.dev1607725349
```

Could you check (without your workaround) that this fit your need and fix your issue with Apollo?

**Comment by daveoconnor** [comment]
Hi,
Thanks for the speedy response!
Have been testing this this morning and it's keeping the connections alive so that's great!

Some notes:

1) The client is still sending the ka even if data has been sent in the recent past. Maybe it makes sense to keep it simpler than to add timer resets to the setup and it's not like it's a lot of data being passed, but thought I'd mention it anyway as a minor detail.
1) I recommend this be set on by default. I suspect most developers won't realise this option is necessary or a cause for their problems - I only noticed it during development because I've been getting frequent unnecessary API hits as the connection re-established itself because Apollo had reconnect on. (It's not specifically an Apollo issue, this seems to be browser based from what I see in searches. https://stackoverflow.com/questions/10585355/sending-websocket-ping-pong-frame-from-browser). Figuring out what was causing my API hits took up a lot of time and I even filed a bug with another project thinking that there was something in their libs that was triggering the queries rather than the websocket connection closing - so I was in a chicken and egg situation trying to figure out if the queries were causing a connection reset, or vice versa. Having it default on will probably save time for other devs.
1) There's a weird quirk I noticed during testing that may be nothing but I'll mention it and see if it makes any sense to you or sets off any alarm bells. Without the keepalive option configured in tartiflette aiohttp the connection would stay open for approximately 50 seconds. With it enabled the connection closes after 30. I noticed this because I initially had my workaround send the ka every 40 seconds but when I tried 40 seconds as an option to tartiflette aiohttp the connection was still closing. I needed to adjust it lower. If you decide to make it default on I'd set about 25 seconds as the default interval.

Tests were done in Chrome and Firefox.

Thanks again! I appreciate the work you all do!

**Comment by Maximilien-R** [comment]
I think we'll keep it simple and stay with a keep alive message at regular time interval, it'll be easier to handle and it's also the way it's implemented by the [subscription-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/blob/b6a185086caad67945683695860ec9b8ac89cdd2/src/server.ts#L271-L281) reference implementation.

I don't know if we should set it by default, I guess most of the client could expect to have a keep alive but the max timeout could be different depending on the client.

For instance, currently, the [subscription-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) which is integrated to our `GraphiQL` interface have a maximum timeout increase to `10` (which has been up to `30` since the [v0.9.7](https://github.com/apollographql/subscriptions-transport-ws/releases/tag/v0.9.7).

If we set it by default we will have to set a low value to avoid breaking currently working integration (GraphiQL for instance works well without keep-alive messages).

@abusi, what do you think about this?

**Comment by abusi** [comment]
@Maximilien-R I think I agree with you, ka shouldn't be on by default, and regardings the delay between ka, I'll say no default value should be provided. 
If you enables it, it is because you want it, so you know the ka intervals you want. IMHO there is no need for a default value there.

This fix seems to be working, i'll say we move forward to merge and release :+1: 
Once again, great work @Maximilien-R 
@daveoconnor thanks again for reporting bugs and using our lib :heart:
